unimportant

diff --git a/git b/git
--- a/git
+++ b/git
@@ -1,6 +1,5 @@
 #!/bin/sh
 
-
 usage() {
 	[ "$1" ] && {
 		echo
@@ -9,32 +8,32 @@ usage() {
 		exit
 	}
 	echo
-	echo " Multigit 0.1 - git wrapper for working with overlaid repos."
+	echo " Multigit 1.0 - git wrapper for working with overlaid repos."
 	echo " Written by Cosmin Apreutesei. Public Domain."
+	echo " See https://github.com/capr/multigit for info."
 	echo
-	echo " USAGE:"
+	echo " USAGE: $ZERO ..."
 	echo
-	echo "   $0 ls-all                          list all known packages"
-	echo "   $0 ls-uncloned                     list not yet cloned packages"
-	echo "   $0 ls-cloned                       list cloned packages"
-	echo "   $0 ls-modified                     list packages that were modified locally"
-	echo "   $0 ls-unpushed                     list packages that are ahead of origin"
-	echo "   $0 ls-untracked                    list files untracked by any repo"
-	echo "   $0 ls-double-tracked               list files tracked by multiple repos"
-	echo "   $0 clone <package> [origin | url]  clone a package"
-	echo "   $0 clone-all [fetch-options]       clone all uncloned packages"
-	echo "   $0 unclone <package>               remove a cloned package from disk (!)"
-	echo "   $0 <package>|--all up [message]    add/commit/push combo"
-	echo "   $0 <package>|--all uptag           update current tag to point to current commit"
-	echo "   $0 <package>|--all ver             show package version"
-	echo "   $0 <package>|--all clear-history   clear the entire history of the current branch (!)"
-	echo "   $0 <package>|--all update-perms    chmod+x all .sh files in package (in git)"
-	echo "   $0 <package>|--all make-symlinks   make symbolic links in .multigit/<package>"
-	echo "   $0 <package>|--all make-hardlinks  make hard links in .multigit/<package>"
-	echo "   $0 <package>|--all command ...     execute any git command on a package repo"
-	echo "   $0 <package>                       start a git subshell for a package repo"
-	echo "   $0 platform                        show current platform"
-	echo "   $0 [help|--help]                   this screen"
+	echo "   ls-all                       list all known packages"
+	echo "   ls-uncloned                  list not yet cloned packages"
+	echo "   ls-cloned                    list cloned packages"
+	echo "   ls-modified                  list packages that were modified locally"
+	echo "   ls-unpushed                  list packages that are ahead of origin"
+	echo "   ls-untracked                 list files untracked by any repo"
+	echo "   ls-double-tracked            list files tracked by multiple repos"
+	echo "   clone [origin/]pkg | url ... clone packages"
+	echo "   clone-all [fetch-options]    clone all uncloned packages"
+	echo "   unclone pkg1 ...             remove cloned packages from disk (!)"
+	echo "   pkg|--all up [message]       add/commit/push combo"
+	echo "   pkg|--all uptag              update current tag to point to current commit"
+	echo "   pkg|--all ver[sion]          show package version"
+	echo "   pkg|--all clear-history      clear the entire history of the current branch (!)"
+	echo "   pkg|--all update-perms       chmod+x all .sh files in package (in git)"
+	echo "   pkg|--all make-symlinks      make symbolic links in .multigit/pkg"
+	echo "   pkg|--all make-hardlinks     make hard links in .multigit/pkg"
+	echo "   pkg|--all command ...        execute any git command on a package repo"
+	echo "   pkg                          start a git subshell for a package repo"
+	echo "   [help|--help]                show this screen"
 	echo
 	exit
 }
@@ -105,59 +104,132 @@ list_double_tracked() {
 }
 
 clone_all() {
-	export GIT_FETCH_OPTS="$@"
+	export MULTIGIT_FETCH_OPTS="$@"
 	for package in `list_uncloned`; do
 		"$0" clone "$package"
 	done
 }
 
-clone() {
-	[ "$1" ] || usage "Package name expected."
-	[ ! -d ".multigit/$1/.git" ] || usage "Package \"$1\" already cloned."
+clone_one() {
+	local arg=$1
+	local name
+	local origin
+	local rorigin
+	local url
 
-	if [ "$2" = "" ]; then
-		[ -f ".multigit/$1.origin" ] || usage "File not found \".multigit/$1.origin\"."
-		o=$(cat .multigit/$1.origin)
-		if [ -f .multigit/$o.baseurl ]; then
-			baseurl=$(cat .multigit/$o.baseurl); url=$baseurl$1
-		else
-			url=$o
-		fi
+	# trim arg
+	arg=${arg# *}
+	arg=${arg%* }
+
+	# check if the arg is a full url or just `[origin/]name`
+	if [ "${arg#*:}" != "$arg" ]; then
+		url=$arg
+		origin=$arg
+		name=${url##*/}
+		name=${name%.git}
 	else
-		origin=$2
+		name=${arg##*/}
+		origin=${arg%/*}
+		[ "$origin" = "$arg" ] && origin=""
+	fi
+
+	# check that the name does not contain spaces or is made of slashes
+	[ "$arg" = "$1" -a "$name" ] || \
+		usage "Invalid package name \"$1\"."
+
+	# check that the package is not already cloned
+	[ -d ".multigit/$name/.git" ] && {
+		echo "ERROR: Already cloned: \"$name\"."
+		return
+	}
+
+	# check for a registered origin
+	[ -f ".multigit/$name.origin" ] && \
+		rorigin=$(cat .multigit/$name.origin)
+
+	# decide the origin
+	if [ "$origin" ]; then
+		[ "$origin" = "$rorigin" ] || \
+			echo "Cloning \"$name\" from different origin \"$origin\" (was \"$rorigin\")."
+	else
+		origin=$rorigin
+		[ "$origin" ] || {
+			echo "ERROR: Missing origin in \".multigit/$name.origin\"."
+			return
+		}
+	fi
+
+	# find the origin url
+	if [ ! "$url" ]; then
 		if [ -f ".multigit/$origin.baseurl" ]; then
-			baseurl=$(cat .multigit/$origin.baseurl); url=$baseurl$1
+			local baseurl=$(cat .multigit/$origin.baseurl)
+			url=$baseurl$name
 		else
-			url=$origin
+			# assume the origin on file is a full url: check if it is
+			if [ "${origin#*:}" != "$origin" ]; then
+				url=$origin
+			else
+				echo "ERROR: Unknown origin: \"$origin\"."
+				return
+			fi
 		fi
 	fi
 
 	# set the .gitignore file for multigit on the first clone operation.
 	git config core.excludesfile .multigit/.exclude
 
-	mkdir -p ".multigit/$1"
-	export GIT_DIR=".multigit/$1/.git"
-
+	# finally, clone the package
+	mkdir -p ".multigit/$name"
+	export GIT_DIR=".multigit/$name/.git"
 	git init
 	git config --local core.worktree ../../..
-	git config --local core.excludesfile ".multigit/$1.exclude"
-	git remote add origin "$url"
-	git fetch $GIT_FETCH_OPTS || {
-		rm -rf ".multigit/$1/.git"
-		usage "git fetch error."
+	git config --local core.excludesfile ".multigit/$name.exclude"
+	git remote add origin $url
+	git fetch $MULTIGIT_FETCH_OPTS || {
+		rm -rf ".multigit/$name/.git"
+		echo "ERROR: git fetch error."
+		return
 	}
 	git branch --track master origin/master
 	git checkout
 
-	# register the package if new
-	[ "$origin" ] && echo $origin > .multigit/$1.origin
+	# make an "exclude-all" exclude file if one is not present
+	[ -f ".multigit/$name.exclude" ] || echo '*' > ".multigit/$name.exclude"
+
+	# if fetch was successful, (re)register the origin for the package
+	if [ "$origin" != "$rorigin" ]; then
+		if [ "$rorigin" ]; then
+			echo "NOTE: Updating origin for \"$name\": \"$origin\" (was \"$rorigin\")"
+		else
+			echo "NOTE: Registering origin for \"$name\": $origin ($url)"
+		fi
+		echo $origin > ".multigit/$name.origin"
+	fi
 }
 
-unclone() {
-	[ "$1" ] || usage "Missing package."
-	[ -d ".multigit/$1/.git" ] || usage "Package not found \"$1\"."
+clone() {
+	[ "$1" ] || usage "Package name expected."
+	if [ $# = 1 ]; then
+		clone_one "$@"
+	else
+		while [ $# != 0 ]; do
+	   	clone_one "$1"
+	   	shift
+	   done
+	fi
+}
 
-	files="$(GIT_DIR=".multigit/$1/.git" git ls-tree -r --name-only HEAD)"
+unclone_one() {
+	[ -d ".multigit/$1/.git" ] || {
+		echo "ERROR: package not found \"$1\"."
+		return
+	}
+
+	# get tracked files for this package
+	files="$(GIT_DIR=".multigit/$1/.git" git ls-tree -r --name-only HEAD)" || {
+		echo "ERROR: could not get files for \"$1\"."
+		return
+	}
 
 	# remove files
 	for file in $files; do
@@ -174,16 +246,21 @@ unclone() {
 	# remove the git dir
 	rm -rf ".multigit/$1/.git"
 	rmdir ".multigit/$1"
+
+	echo "Removed: \"$1\"."
 }
 
-platform() {
-	[ "$PROCESSOR_ARCHITECTURE" = "AMD64" -o "$PROCESSOR_ARCHITEW6432" = "AMD64" ] && echo mingw64 || {
-		[ "$OSTYPE" = "msys" ] && echo mingw32 || {
-			local a=32
-			[ "$(uname -m)" = "x86_64" ] && a=64
-			[ "${OSTYPE#darwin}" != "$OSTYPE" ] && echo osx$a || echo linux$a
-		}
-	}
+unclone() {
+	[ "$1" ] || usage "Package name expected."
+	[ "$GIT_DIR" ] && usage "Refusing to unclone from a subshell."
+	if [ $# = 1 ]; then
+		unclone_one "$@"
+	else
+		while [ $# != 0 ]; do
+	   	unclone_one "$1"
+	   	shift
+	   done
+	fi
 }
 
 git_shell() {
@@ -191,7 +268,12 @@ git_shell() {
 	echo "Type \`exit' to exit subshell."
 	git status -s
 	echo
-	PS1="[$MULTIGIT_PACKAGE] \u@\h:\w\$ " $SHELL -i
+	if [ "$OSTYPE" = "msys" ]; then
+		export PROMPT="[$MULTIGIT_PACKAGE] $P$G"
+		exec "$COMSPEC" /k
+	else
+		PS1="[$MULTIGIT_PACKAGE] \u@\h:\w\$ " $SHELL -i
+	fi
 }
 
 git_up() {
@@ -251,7 +333,7 @@ git_make_symlinks() {
 }
 
 git_cmd() {
-	[ "$1" = "--all" -o "$1" = "-a" ] && {
+	[ "$1" = "--all" ] && {
 		shift
 		[ "$@" ] || usage "Refusing to start a subshell for each package."
 		foreach_cloned "$@"
@@ -263,12 +345,12 @@ git_cmd() {
 
 	export GIT_DIR=".multigit/$pkg/.git"
 	export MULTIGIT_PACKAGE="$pkg"
-	[ -d "$GIT_DIR" ] || usage "Unknown package \"$pkg\"."
+	[ -d "$GIT_DIR" ] || usage "Unknown package: \"$pkg\"."
 
 	[ "$1" ] || { git_shell; exit; }
 	[ "$1" = "up" ] && { git_up "$2"; exit; }
 	[ "$1" = "uptag" ] && { git_uptag; exit; }
-	[ "$1" = "ver" ] && { git_ver; exit; }
+	[ "$1" = "ver" -o "$1" = "version" ] && { git_ver; exit; }
 	[ "$1" = "clear-history" ] && { git_clear_history; exit; }
 	[ "$1" = "update-perms" ] && { git_update_perms; exit; }
 	[ "$1" = "make-symlinks" ] && { git_make_symlinks; exit; }
@@ -277,11 +359,10 @@ git_cmd() {
 	git "$@"
 }
 
+[ "$ZERO" ] || ZERO="$0" # for wrapping
 cd "$(dirname "$0")" || usage "Could not change dir to \"$(dirname "$0")\"."
 
-[ "$1" ] || usage
-[ "$1" = "help" ] && usage
-[ "$1" = "--help" ] && usage
+[ -z "$1" -o "$1" = "help" -o "$1" = "--help" ] && usage
 [ "$1" = "ls-all" ] && { list_known; exit; }
 [ "$1" = "ls-cloned" ] && { list_cloned; exit; }
 [ "$1" = "ls-uncloned" ] && { list_uncloned; exit; }
@@ -292,6 +373,5 @@ cd "$(dirname "$0")" || usage "Could not change dir to \"$(dirname "$0")\"."
 [ "$1" = "clone" ] && { shift; clone "$@"; exit; }
 [ "$1" = "clone-all" ] && { shift; clone_all "$@"; exit; }
 [ "$1" = "unclone" ] && { shift; unclone "$@"; exit; }
-[ "$1" = "platform" ] && { platform; exit; }
 
 git_cmd "$@"
